"""Schema helpers for VLA-style FSM demonstration recording.

Step 14 scope:
- no OpenVLA import
- no model inference
- no replay
- no runtime control changes

This schema stores observations and teacher actions generated by the existing
FSM baseline. The FSM is the teacher; the VLA branch only records data here.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any
import json
import numpy as np


@dataclass(frozen=True)
class VLADemoStep:
    """One synchronized image/action record from an FSM teacher rollout."""

    step_index: int
    sim_time: float
    image_path: str
    instruction: str
    phase: str
    palm_world: tuple[float, float, float]
    pelvis_pos: tuple[float, float, float]
    pelvis_quat: tuple[float, float, float, float]
    reach_target_pelvis: tuple[float, float, float]
    grip_closed: bool
    action_7d: tuple[float, float, float, float, float, float, float]


def as_float_tuple(value: Any, length: int, name: str) -> tuple[float, ...]:
    """Convert *value* to a tuple of Python floats with the required *length*.

    Raises ValueError if the resulting array does not have shape (*length*,).
    """
    arr = np.asarray(value, dtype=np.float64)
    if arr.shape != (length,):
        raise ValueError(f"{name} must have shape ({length},), got {arr.shape}")
    return tuple(float(x) for x in arr)


def make_action_7d(
    current_palm_world: np.ndarray,
    next_palm_world: np.ndarray,
    grip_closed: bool,
) -> tuple[float, float, float, float, float, float, float]:
    """Compute a 7D teacher action from consecutive palm positions.

    Returns (dx, dy, dz, 0, 0, 0, gripper) where rotation is intentionally
    zero for Step 14 and gripper is 1.0 when closed, 0.0 when open.
    """
    current = np.asarray(current_palm_world, dtype=np.float64)
    nxt = np.asarray(next_palm_world, dtype=np.float64)
    if current.shape != (3,):
        raise ValueError(
            f"current_palm_world must have shape (3,), got {current.shape}"
        )
    if nxt.shape != (3,):
        raise ValueError(
            f"next_palm_world must have shape (3,), got {nxt.shape}"
        )
    delta = nxt - current
    return (
        float(delta[0]),
        float(delta[1]),
        float(delta[2]),
        0.0,
        0.0,
        0.0,
        1.0 if bool(grip_closed) else 0.0,
    )


def step_to_json(step: VLADemoStep) -> str:
    """Serialise *step* to a compact JSON string (no trailing newline)."""
    return json.dumps(asdict(step), separators=(",", ":"))


def step_from_json(line: str) -> VLADemoStep:
    """Parse a single JSON line into a VLADemoStep."""
    data = json.loads(line)
    return VLADemoStep(
        step_index=int(data["step_index"]),
        sim_time=float(data["sim_time"]),
        image_path=str(data["image_path"]),
        instruction=str(data["instruction"]),
        phase=str(data["phase"]),
        palm_world=as_float_tuple(data["palm_world"], 3, "palm_world"),
        pelvis_pos=as_float_tuple(data["pelvis_pos"], 3, "pelvis_pos"),
        pelvis_quat=as_float_tuple(data["pelvis_quat"], 4, "pelvis_quat"),
        reach_target_pelvis=as_float_tuple(
            data["reach_target_pelvis"], 3, "reach_target_pelvis"
        ),
        grip_closed=bool(data["grip_closed"]),
        action_7d=as_float_tuple(data["action_7d"], 7, "action_7d"),
    )


def write_jsonl(path: str | Path, steps: list[VLADemoStep]) -> None:
    """Write *steps* as a JSONL file at *path*, creating parent dirs as needed."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        for step in steps:
            f.write(step_to_json(step) + "\n")


def read_jsonl(path: str | Path) -> list[VLADemoStep]:
    """Read a JSONL file and return a list of VLADemoStep objects."""
    src = Path(path)
    steps: list[VLADemoStep] = []
    with src.open("r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped:
                steps.append(step_from_json(stripped))
    return steps
